### ISSUE TITLE
Can't upgrade new version for .Net 4.5 app

### ISSUE THREAD

**Issue by Tsury** [XieJJ99/brotli.net#15]
Getting this error:
https://i.imgur.com/lHCCCL5.png

**Comment by XieJJ99** [comment]
@Tsury Thanks for the feedback.
In order to support .NET Core and Linux, the minimum requirement of this package is .NET Standard 2.
For .NET framework, it's .NET framework v4.6.1 and above. For .NET core, it's .NET Core 2.0 and above.
Just as the IDE prompts, your framework version is not compatible with V2.
For compability, you could check:
[.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
You have two choices:

1. Retargeting the project to .NET framework **v4.6.1** and above
2. Stay at version v1.0.0.19

Please contact me if any other issues.

**Comment by XieJJ99** [comment]
@Tsury Now the new package supports .NET Framework 3.5 and above, you can try v2.0.4.2.

**Comment by Tsury** [comment]
Thank you!
